version: '3'
services:
    web:
        image: data-extractor
        volumes:
            - ./scripts:/usr/src/app/scripts
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
