version: '3'

services:
  web:
    build: .
    image: my-website:latest
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web
