version: '3'
services:
    web:
        build:
            context: .
        volumes:
            - ./scripts:/usr/src/app/scripts
        depends_on:
            - nginx
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf  # Actualización aquí
        ports:
            - "8081:80"
