version: '3'
services:
    web:
    build:
      context: .
    volumes:
      - ./scripts:/usr/src/app/scripts
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
