name: Data Extraction

on:
  schedule:
    # Every 15 minutes from 7:30 to 22:00 on Monday to Friday
    - cron: '30/15 7-21 * * 1-5'
    - cron: '0-15/15 22 * * 1-5'
    # Every 15 minutes from 8:30 to 20:00 on Saturday
    - cron: '30/15 8-19 * * 6'
    - cron: '0-15/15 20 * * 6'
    # Every 15 minutes from 8:30 to 14:00 on Sunday
    - cron: '30/15 8-13 * * 0'
    - cron: '0-15/15 14 * * 0'

jobs:
  extract-data:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install requests_html

    - name: Run data extraction script
      run: |
        python scripts/data_extractor.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add -A
        git commit -m "Update data" -a || echo "No changes to commit"
        git push
